apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonar-data
  namespace: devops
spec:
  storageClassName: "hostpath"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
