apiVersion: v1
kind: Service
metadata:
  name: sonar-service
  namespace: lcf-k8s-devops
  labels:
    app: sonarqube
spec:
  selector:
    app: sonarqube
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 31500
      name: sonar-port