apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: artp-devops
  labels:
    app: jenkins
    criticity: high
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin-clusterrole
  namespace: artp-devops
  labels:
    app: jenkins
    criticity: high
rules:
- apiGroups: [ "" ]
  resources: [ "*" ]
  verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin-clusterrolebinding
  namespace: artp-devops
  labels:
    app: jenkins
    criticity: high
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-admin-clusterrole
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: artp-devops
